name = "pomodoro-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "pomodoro-db"
database_id = "84f5543d-e0b0-45cd-96e1-0d55f8c620bf"

[[kv_namespaces]]
binding = "KV"
id = "0670d94f25ce4f51bf492034aa840d43"

[vars]
BETTER_AUTH_SECRET = "dev-secret-change-in-production"
BETTER_AUTH_URL = "http://localhost:8787"
